### PR TITLE
Check for duplicated projects

### PR DESCRIPTION
**Pull request by javierpena**
This commit is adding a check when loading the YAML file, to verify
there are no duplicated projects. Right now, checking for project
name and upstream repo, as this can break Delorean.

### CODE REVIEW

**Comment by javierpena** [comment]
Why is Travis trying to run rake?

**Comment by apevec** [comment]
B/c I started configuring it for rdoinfo repo and rake seems to be oh-so-ruby-default :)

We need to add travis.yml - I see OPM has it so we can copy it and adjust.

**Comment by apevec** [comment]
@javierpena initial config in https://github.com/redhat-openstack/rdoinfo/pull/88 but needs more work https://travis-ci.org/redhat-openstack/rdoinfo/builds/79689835

**Comment by apevec** [comment]
@javierpena please rebase this PR, I've pushed .travis.yml

**Pull request merged**
