### PR TITLE
Add trove and sahara dashboard

### PR DESCRIPTION
**Pull request by hguemar**
Please review @egafford @pdmack @vkmc

```
dlrn --info-repo ~/.rdopkg/rdoinfo --config-file projects.ini  --package-name openstack-sahara-ui
INFO:dlrn:Getting git://github.com/openstack-packages/sahara-dashboard to ./data/openstack-sahara-ui_distro
INFO:dlrn:Getting git://git.openstack.org/openstack/sahara-dashboard to ./data/openstack-sahara-ui
INFO:dlrn:Processing openstack-sahara-ui 466690137f6ee6b4445ee1effd6bd13e87901340
INFO:dlrn:128 packages not built correctly: not updating the consistent symlink
% dlrn --info-repo ~/.rdopkg/rdoinfo --config-file projects.ini  --package-name openstack-trove-ui 
INFO:dlrn:Getting git://github.com/openstack-packages/trove-dashboard to ./data/openstack-trove-ui_distro
INFO:dlrn:Getting git://git.openstack.org/openstack/trove-dashboard to ./data/openstack-trove-ui
INFO:dlrn:Processing openstack-trove-ui 7ff6706b09d1375de7726e9fb948babd56792d02
INFO:dlrn:127 packages not built correctly: not updating the consistent symlink
% ls data/repos/current 
build.log                                                           openstack-sahara-ui-4.0.0.0-0.20160413183229.4666901.el7.centos.noarch.rpm  python-oslotest-2.3.1-0.20160317151307.4150952.fc23.src.rpm
delorean.repo                                                       openstack-sahara-ui-4.0.0.0-0.20160413183229.4666901.el7.centos.src.rpm     repodata
installed                                                           openstack-trove-ui-6.0.0.0-0.20160413183746.7ff6706.el7.centos.noarch.rpm   root.log
mock.log                                                            openstack-trove-ui-6.0.0.0-0.20160413183746.7ff6706.el7.centos.src.rpm      rpmbuild.log
openstack-manila-ui-2.0.0-0.20160222174515.bf38208.fc23.noarch.rpm  python2-oslotest-2.3.1-0.20160317151307.4150952.fc23.noarch.rpm             state.log
openstack-manila-ui-2.0.0-0.20160222174515.bf38208.fc23.src.rpm     python3-oslotest-2.3.1-0.20160317151307.4150952.fc23.noarch.rpm             versions.csv
```

### CODE REVIEW

**Comment by pdmack** [comment]
Seems ok?

**Comment by egafford** [comment]
Are we alright with the repos at the distgit level not mapping to the name of the packages? The core config will have the distgits at sahara-dashboard and trove-dashboard, while they emit packages openstack-sahara-ui and openstack-trove-ui. This may be awesome and in keeping with other repos, but I figure I should ask.

**Comment by hguemar** [comment]
we should be fine, but the packages will be consistent with their predecessor openstack-manila-ui

**Comment by hguemar** [comment]
we also have openstack-app-catalog-ui too

**Comment by egafford** [comment]
Sounds good then, and yes, the package naming is correct (per conversation with apevec) which is certainly the most critical bit. Thanks Haikel!

**Pull request merged**
