### PR TITLE
Add Manila in Delorean

### PR DESCRIPTION
**Pull request by hguemar**

### CODE REVIEW

**Comment by hguemar** [comment]
Please @apevec @zaitvec

**Comment by apevec** [comment]
+1 https://github.com/openstack-packages/manila looks good, minor cleanup would be to truncate .gitignore and sources
@hguemar  could you also confirm you verified it builds with Delorean locally?

**Comment by zaitcev** [comment]
Looks fine to me but I don't have a clue about DeLorean.

**Comment by hguemar** [comment]
@zaitcev no problem, if you're ok with the information provided, it's all good.

@apevec done, and it works locally as this excerpt from my shell

```bash
$ delorean --config-file projects.ini --local --package-name openstack-manila --dev  --info-repo /home/hguemar/rdoinfo/
INFO:delorean:Getting git://github.com/openstack-packages/manila to ./data/openstack-manila_distro
INFO:delorean:Getting git://git.openstack.org/openstack/manila to ./data/openstack-manila
INFO:delorean:Processing openstack-manila 4d460e9ce0e814952bcca401dfbe56d230850fec
$ ls data/repos/current 
delorean.repo      installed                                       openstack-manila-2015.2-dev107.fc21.src.rpm         openstack-manila-share-2015.2-dev107.fc21.noarch.rpm  repodata
distro_delta.diff  openstack-manila-2015.2-dev107.fc21.noarch.rpm  openstack-manila-doc-2015.2-dev107.fc21.noarch.rpm  python-manila-2015.2-dev107.fc21.noarch.rpm           rpmbuild.log
```

**Pull request merged**
