### PR TITLE
Adding networking-cisco to rdo.yml

### PR DESCRIPTION
**Pull request by bdemers**
This pull request serves as a little more then just updating `rdo.yml`

I've added a spec repo here [networking-cisco-packages](https://github.com/bdemers/networking-cisco-packages) which hopefully would be moved to openstack-packages/python-networking-cisco

Please have a look at both the `rdo.yml` and [networking-cisco-packages](https://github.com/bdemers/networking-cisco-packages) let me know what you think.

**Update:** openstack-packages/python-networking-cisco as added

### CODE REVIEW

**Comment by apevec** [comment]
https://github.com/bdemers/networking-cisco-packages/blob/rpm-master/networking-cisco.spec looks fine, only one minor change https://github.com/bdemers/networking-cisco-packages/commit/9effebc8af5a3b57a163da0912fa36685b8132cf#commitcomment-11896777 before importing to openstack-packages.

**Comment by bdemers** [comment]
@apevec thanks, 'Release' has been updated. let me know if there is anything else I should do

**Comment by apevec** [comment]
+1 from me to import to openstack-packages/networking-cisco

Neutron folks, @booxter @mangelajo please review https://github.com/bdemers/networking-cisco-packages/blob/rpm-master/networking-cisco.spec before import!

**Comment by booxter** [comment]
NAK from me. There are multiple problems in the spec that should be fixed before import to delorean:

- the package name does not contain 'neutron' at all.
- we should be consistent with other vendor packages: those are already named like python-networking-<vendor>, so it should be the case for cisco repo.
- I want us to avoid diverging from other vendor specs. Please reuse as much of those: https://github.com/openstack-packages/python-networking-mlnx/blob/rpm-master/networking_mlnx.spec Note how it uses the same template for different vendors, you only update the %{vendor} macro value, and stick to similar spec structure.
- you should not rewrite BuildRoot or Prefix.
- Group is not needed anymore.
- %clean is not needed.
- most of those arguments: --single-version-externally-managed -O1 --root=$RPM_BUILD_ROOT --record=INSTALLED_FILES are also not needed.
- not sure why you even define that INSTALLED_FILES.
- what's that defattr for?
- I don't see you doing %systemd_post.
- I don't see systemd-units in BuildRequires.

Please make your spec reflect the usual vendor package.

**Comment by booxter** [comment]
One more thing: your service file should probably belong to a separate subpackage, and it should handle configuration files in the same way as neutron does, f.e. reading conf.d/<service-name>.

**Comment by bdemers** [comment]
@booxter thanks for the ref to mnlx, i didn't see that  (or the other two -networking projects originally, not sure how I missed them now...)

I'll get this cleaned up, I was guessing starting with the generated spec, might not be the best, but just not sure how _bad_ it was.

**Comment by bdemers** [comment]
@booxter 
should this spec obsolete openstack-neutron-cisco and openstack-quantum-cisco ?

I noticed, the others under openstack-pacakages didn't, but figured i'd ask.

**Comment by bdemers** [comment]
@booxter I updated the spec, I think this addresses all of your comments. (using the mlnx as the base helped with that)

Open question, about about marking packages obsolete, still open.

Anything else I should look at ?

**Comment by booxter** [comment]
Can we replace multiple 'mv' calls in %install with a single one, in case more ini files emerge in the tree?

mv %{buildroot}/usr/etc/neutron/* %{buildroot}%{_sysconfdir}/neutron/

Same for %files.

Also, you forgot to update your .service file to read conf.d directories: --config-dir /etc/neutron/conf.d/common --config-dir /etc/neutron/conf.d/neutron-cisco-cfg-agent

Overall, looks cool. Once you update that, I'm happy to see it merged.

**Comment by booxter** [comment]
As for relation with openstack-neutron-cisco subpackage, I'm not sure. Is it the same contents? Why do we maintain them inside neutron tree then?

**Comment by bdemers** [comment]
It replaces it, I think this work was just missed after the vendor decomp.
After this stuff gets in, those bits should be removed. This is one of the reasons i was asking about the the obsoletes

**Comment by booxter** [comment]
In openstack-neutron-cisco, I still see the following executables packaged:

%{_bindir}/neutron-cisco-apic-host-agent
%{_bindir}/neutron-cisco-apic-service-agent

while they are not present in your package. Ideas why?

I think we should make sure those bits are cleaned up from upstream tree, otherwise we end up with conflicting packages. And yes, once it's done, we should probably obsolete the -cisco subpackage.

**Comment by bdemers** [comment]
@HenryGessau added `neutron-cisco-cfg-agent`, 
Any idea on `neutron-cisco-apic-host-agent` and `neutron-cisco-apic-service-agent`, I'm assuming they are safe to drop ? Can you confirm ?
they both use: `neutron.plugins.ml2.drivers.cisco.apic.apic_topology:service_main`
and `neutron-cisco-cfg-agent` uses `networking_cisco.plugins.cisco.cfg_agent.cfg_agent:main`

**Comment by bdemers** [comment]
Updated bdemers/networking-cisco-packages

**Comment by booxter** [comment]
+2 to merge in delorean. @apevec, please accomodate. ;)
@bdemers, welcome to Delorean packagers! :)

**Comment by bdemers** [comment]
Thanks!
@apevec, once the repo is added to openstack-packages/networking-cisco, I can update `rdo.yml`

**Comment by apevec** [comment]
To align with other networking vendor libs ( https://github.com/openstack-packages/?query=networking ) I'll import bdemers/networking-cisco-packages as openstack-packages/python-networking-cisco and also rename spec file to match the package name: https://fedoraproject.org/wiki/Packaging:NamingGuidelines#Spec_file_name

**Comment by apevec** [comment]
All set https://github.com/openstack-packages/python-networking-cisco/commits/rpm-master

I pushed spec file rename + master packaging diff

**Comment by bdemers** [comment]
Thanks @apevec ! I've updated this pull request to reflect that

**Pull request merged**
