### PR TITLE
Add dprince as a co-maintainer of mistral

### PR DESCRIPTION
**Pull request by dprince**

### CODE REVIEW

**Comment by dprince** [comment]
@apevec @hguemar Hows this look?

**Comment by apevec** [comment]
:-1: I'd prefer folks from Mirantis who provided initial spec draft

**Comment by trown** [comment]
@apevec we will be using mistral heavily in tripleo, so it seems ok to have Dan as co-maintainer. Is there a specific reason we need a Mirantis person as maintainer?

**Comment by apevec** [comment]
Migrating to review.rdoproject.org

**Pull request closed without merging**
