### PR TITLE
Opm from master patches

### PR DESCRIPTION
**Pull request by apevec**
This can be merged when all of https://review.gerrithub.io/#/q/topic:opm-from-master-patches is merged AND running in production!
@yac @strider @derekhiggins @dprince @javierpena @alobbs please review this PR and patches above.

### CODE REVIEW

**Comment by javierpena** [comment]
Tested, it works for me and creates a correct package once https://review.gerrithub.io/#/c/217320/2 is applied. Note I had to change build_opm_rpm.sh slightly to make it work.

+1 for me.

**Comment by apevec** [comment]
@alobbs merge was premature https://review.gerrithub.io/#/q/topic:opm-from-master-patches is fully merged!

**Comment by derekhiggins** [comment]
I've just merged the delorean commit and will move it to into production now

**Comment by derekhiggins** [comment]
@apevec  ^^

**Comment by apevec** [comment]
Cool beans, thanks @derekhiggins

**Comment by apevec** [comment]
@derekhiggins new OPM spec https://review.gerrithub.io/217117 is also required with this new OPM rdoinfo entry

**Comment by derekhiggins** [comment]
@apevec merged and both deloreans are now updated with current master and seem to be running ok.

**Pull request merged**
